networks:
  seamless-provider-monorepo:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: ${APP_NAME}_nginx
    ports:
      - 8000:80
    links:
      - php
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/log/nginx:rw
    depends_on:
      - php
      - postgres
    networks:
      - seamless-provider-monorepo

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_php
    volumes:
      - ./:/var/www/html
    ports:
      - 9002:9000
    networks:
      - seamless-provider-monorepo

  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}_postgres
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - db-volumes:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_DB=${DB_DATABASE}
      - PGDATA=/var/lib/postgresql/data/pgdata
      - TZ=UTC
      - PG_TZ=UTC
    networks:
      - seamless-provider-monorepo

volumes:
  db-volumes:
